### ISSUE TITLE
Excluding certain resource changes

### ISSUE THREAD

**Issue by ricardofalc** [borchero/terraform-plan-comment#28]
Hi,

I am for example planning changes in resources against production.
But because the staging environment, has a different service principal for authentication and for example a different database connection string then production. 

Each PR consistently marks this as a change, which is correct.
Is it possible to maybe introduce something where you can exclude these changes?

Or would this make it way too complex and make it prone to errors?

**Comment by borchero** [comment]
I think it would be very feasible to provide a list of resource paths (+effect? i.e. `change`/`update`/...) that should be excluded from the comment pasted to the PR. Obviously, this would come with some caveats (do you really want the PR to show "no changes" if there's a diff in this resource path?) but I guess the user will be aware of the implications.

One potential addition could be the following:

```yaml
- name: Post PR comment
  uses: borchero/terraform-plan-comment@v2
  with:
    token: ${{ github.token }}
    planfile: .planfile
    ignore-resources: |
      local_file.another
```

or, including the effect:

```yaml
- name: Post PR comment
  uses: borchero/terraform-plan-comment@v2
  with:
    token: ${{ github.token }}
    planfile: .planfile
    ignore-changes: |
      update local_file.another
```

Wdyt? Would you be interested in contributing?
